apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-app
  labels:
    app: search-service-app
spec:
  selector:
    matchLabels:
      app: search-service-app
  template:
    metadata:
      labels:
        app: search-service-app
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: search-service-app
          image: janescience/search-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086

