apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service-app
  labels:
    app: search-service-app
spec:
  revisionHistoryLimit: 0
  replicas: 3
  selector:
    matchLabels:
      app: search-service-app
  template:
    metadata:
      labels:
        app: search-service-app
    spec:
      containers:
        - name: search-service-app
          image: janescience/search-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
