apiVersion: v1
kind: Service
metadata:
  name: search-service-app
  labels:
    app: search-service-app
spec:
  ports:
    - protocol: TCP
      name: http-traffic
      port: 80
      targetPort: 8086
  selector:
    app: search-service-app